export default {
  users: [
    {
      id: 1,
      name: 'Smith',
      gender: 'Male',
      age: 34,
      skills: 'Java',
    },
    {
      id: 2,
      name: 'David',
      gender: 'Male',
      age: 28,
      skills: 'Java',
    },
    {
      id: 3,
      name: 'Alice',
      gender: 'Female',
      age: 29,
      skills: 'Python',
    },
    {
      id: 4,
      name: 'Sophia',
      gender: 'Female',
      age: 32,
      skills: 'JavaScript',
    },
    {
      id: 5,
      name: 'John',
      gender: 'Male',
      age: 24,
      skills: 'C++',
    },
    {
      id: 6,
      name: 'Emma',
      gender: 'Female',
      age: 26,
      skills: 'Ruby',
    },
    {
      id: 7,
      name: 'Lucas',
      gender: 'Male',
      age: 31,
      skills: 'Swift',
    },
    {
      id: 8,
      name: 'Olivia',
      gender: 'Female',
      age: 27,
      skills: 'Kotlin',
    },
    {
      id: 9,
      name: 'Ethan',
      gender: 'Male',
      age: 22,
      skills: 'Go',
    },
    {
      id: 10,
      name: 'Isabella',
      gender: 'Female',
      age: 25,
      skills: 'C#',
    },
    {
      id: 11,
      name: 'Mason',
      gender: 'Male',
      age: 40,
      skills: 'PHP',
    },
    {
      id: 12,
      name: 'Evelyn',
      gender: 'Female',
      age: 35,
      skills: 'Rust',
    },
    {
      id: 13,
      name: 'Alexander',
      gender: 'Male',
      age: 33,
      skills: 'Scala',
    },
    {
      id: 14,
      name: 'Lily',
      gender: 'Female',
      age: 30,
      skills: 'HTML, CSS',
    },
    {
      id: 15,
      name: 'Benjamin',
      gender: 'Male',
      age: 29,
      skills: 'TypeScript',
    },
  ],
};
